Function changes
szeged/blurmock pull request #1
Opened 2016-09-15 12:41 UTC by fokinv

Changed the get_uuids() to get the uuids from the struct of the service when invoked, so we don't have to set the uuid vector manually in the tests.
Grouped the methods, the ones created with a macro are first, then the others.

2016-09-15 12:55 UTC, dati91 commented
CC @zakorgy

2016-09-15 13:09 UTC, dati91 commented on src/fake_device.rs
> +        let cloned = self.uuids.clone();
You should remove the `uuids` from the Device struct and remove the `set_uuids` as well.

2016-09-15 13:10 UTC, dati91 requested changes

2016-09-15 15:21 UTC, fokinv commented
@dati91 @zakorgy r?

2016-09-16 08:24 UTC, zakorgy commented
lgtm

2016-09-16 08:27 UTC, dati91 approved these changes

2016-09-16 08:28 UTC, dati91 commented
lgtm, but first squash the 2 uuid-s commits

2016-09-19 08:19 UTC, merged